### ISSUE TITLE
Dal Maso et al data / Cereatti paper data

### ISSUE THREAD

**Issue by fmoissenet** [Ipuch/spartacus-shoulder-kinematic-dataset#102]
I finally understood why I was not able to reproduce the displacements reported in Fig. 2 in Dal Maso et al. 2014.
The scapula coordinate system is translated first in the location of the center of the humerus coordinate system recorded during a "relaxed position trial". However, this trial has not been made available in Cereatti et al. 2017 dataset.

**Comment by fmoissenet** [comment]
If we admit that Engauge method is not possible on Fig. 2 (superimposition of many curves), then GH displacements are not available for this dataset.

**Comment by fmoissenet** [comment]
I have gimbal lock issues using YXY on Dal Maso et al data set. I think I will express all data related to GH rotations using XZY rather than YXY to avoid that.

**Comment by fmoissenet** [comment]
Before to decide, would you please check what you obtain from your side (@ANaaim )? I can provide rotation matrices ...

**Comment by Ipuch** [comment]
I'm on it

**Comment by Ipuch** [comment]
Extracted from biorbd, left to @fmoissenet for formatting to our database :)

**Comment by Ipuch** [comment]
I push again the data on our sharepoint.

**Comment by Ipuch** [comment]
Done in #143
