### ISSUE TITLE
Proposal for Evaluating and Ranking Data Risks

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#115]
@ANaaim @fmoissenet,

Following #25

I propose a systematic approach to evaluate and rank the possible combinations of risks associated with our data. The aim is to identify and quantify the risks involved in different configurations and prioritize them based on **a cumulative risk score**.

**Methodology**:

**Risk Categorization:**
We have identified five categories, each with specific risk options:

- Medical Imagery: Yes (No risk), No (Small risk)
- Intracortical Pins: Without Imagery (Small risk), With Imagery (No risk)
- Thorax is the global frame: No (No risk), Yes (Medium risk).  **Added lately : 22/11/2023**
- Thoraco-humeral Angle: Euler Angles (No risk), Projected Angle (Medium risk), User Controlled Angle (High risk)
- Parent Segment Frame: ISB (No risk), ISB-like (Small risk), Literature Correction (Small risk), ISB-like and Literature Correction (High risk)
- Child Segment Frame: ISB (No risk), ISB-like (Small risk), Literature Correction (Small risk), ISB-like and Literature Correction (High risk)

**Risk Quantification**:
We assign numerical values to the risk levels as follows (example, I'm open):

- No risk: 0
- Small risk: 2
- Medium risk: 4
- High risk: 9

**Combination Generation**:
We generate all possible combinations of the options across the five categories.

**Cumulative Risk Calculation**:
For each combination, we calculate the cumulative risk by summing the risk values of the individual options.

**Risk Ranking**:
We sort all the combinations by their cumulative risk scores.

**Output**:
A CSV file has been generated containing all the possible combinations along with their cumulative risk scores. This will help us to identify the configurations with the least and the most risk.

[risk_combinations.csv](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/files/13232111/risk_combinations.csv)

**Examples** :

Cumulative Risk: 0
```
Medical Imagery: Yes (Risk: 0)
Intracortical Pins: With Imagery (Risk: 0)
Thoraco-humeral Angle: Euler Angles (Risk: 0)
Parent Segment Frame: ISB (Risk: 0)
Child Segment Frame: ISB (Risk: 0)
```

Cumulative Risk: 2
```
Medical Imagery: Yes (Risk: 0)
Intracortical Pins: With Imagery (Risk: 0)
Thoraco-humeral Angle: Euler Angles (Risk: 0)
Parent Segment Frame: ISB (Risk: 0)
Child Segment Frame: ISB-like (Risk: 2)
```

## Benefits:
This approach provides a comprehensive and quantifiable understanding of the risks associated with each combination. It allows us to inform readers on the quality of the data for comparison purpose.

I would appreciate your thoughts and feedback on this proposition.

**Comment by ANaaim** [comment]
Great suggestion !

Some first thought : 
- For the final scoring, it might be interesting to have something more with highest risk found accross category ==> There is no element more important than other and for example I would rather use something with small risk everywhere than a High risk somewhere (maybe integrate both information in the final scoring)

- Also in the individual item, maybe add something about the fact that the Thorax is measured might be interesting (as I remembers in some article no thorax were found)

That are my first impression on the subject but overall i agree with everything :)

**Comment by Ipuch** [comment]
Flo 0,1,2,3 on the metrics.
And verify the coherence then.

**Comment by Ipuch** [comment]
add thorax is global in the metric.

**Comment by Ipuch** [comment]
- We don't want cases where the cumulative small risks == one high risk.
- We may rename the concept to "compliant metric with ISB standard"?

**Comment by Ipuch** [comment]
done in #129
