### ISSUE TITLE
Plot Data for article

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/spartacus-shoulder-kinematic-dataset#120]
A first version of a typical graph. 

Some question on what should be on each graph : 
Idealy, I would have one graph per Joint .... however we might have to much data for that. 

Here each color is an article and each shape a movement. 

Note : Yellow is a bad color, I should remove it. 

![image](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/assets/33746865/40d90515-7a3b-4db2-9ba4-927d6e5efde5)

**Comment by ANaaim** [comment]
When too much data.... very unreadable... 

![image](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/assets/33746865/1ad8d368-0071-481f-a4e5-881691a0fa03)

**Comment by Ipuch** [comment]
Thanks Alex,

I'd rather like displaying one axe by dof by joint.
Otherwise it's bearly readable.

It means translation should be another figure.

**Comment by ANaaim** [comment]
Any way, showing all the result will be bearly readable anyway....We have to choose what we would like to show...

Currently it is impossible to know from the data if an DoF is from Angle or Translation so data ploted might be from the 

Function allowing to choose the joint analysed and the movement plotted (if no movement is given all movement are plotted)

![image](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/assets/33746865/3663939c-0230-4cbe-8435-3ad5254704d8)

![image](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/assets/33746865/f0c2dafd-f145-407f-885d-8eaa2fa92e02)
