### ISSUE TITLE
TODO end of march : Where the calculation of the risk should be done : 

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/spartacus-shoulder-kinematic-dataset#122]
As a reminder : 

https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/blob/58770e046080b445e726b9dff2c5329c9cf4fd41/spartacus/src/row_data.py#L392

**Comment by ANaaim** [comment]
We should also populated the following information in the data : 

```python
toto = spartacus.load()
toto.confident_data_values.angle_translation
```
Currently the field angle_translation is empty and should be flexion extension abduction adduction or rotation interne externe or the equivalent for translation .

**Comment by ANaaim** [comment]
Currently it seems only angle are exported : 
@Ipuch  do you confirm ?

**Comment by Ipuch** [comment]
True, would you like a coordinated coding session next week ?

**Comment by ANaaim** [comment]
No direct information in the data set to evaluate if the direction is not ISB ==> probably we will have to infere from other information.

**Comment by ANaaim** [comment]
@Ipuch and @fmoissenet  : Can I do a pull request for the calculation of the risk to facilitate discussion ?

**Comment by Ipuch** [comment]
Yes !
