### ISSUE TITLE
How to be sure that a segment has a wrong direction issue  ? 

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/spartacus-shoulder-kinematic-dataset#124]
No direct information in the data set to evaluate if the direction is not ISB ==> probably we will have to infere from other information.

**Comment by ANaaim** [comment]
Add a other collumn in the data ?

**Comment by Ipuch** [comment]
As far as I remember, all correctable segment are kept.
So I already, find how to correct issues.
The Methods to check might be a in segment class.

**Comment by Ipuch** [comment]
There was no way to know expect from "is_isb" column in the table so, we decided to put the marker in the database as Flo already did the work. 
#126
