### ISSUE TITLE
[TO DO] Check Graichen et al.

### ISSUE THREAD

**Issue by fmoissenet** [Ipuch/spartacus-shoulder-kinematic-dataset#37]
No useful answers from authors
Many strange values in the extraction table
Need for Sulkar et al. correction (humerus) but actually not usable here (geometrical info missing for that)
Keep or not this paper?

**Comment by Ipuch** [comment]
I vote for excluding the data. Please tell me if you agree to take actions.
@fmoissenet @ANaaim

**Comment by ANaaim** [comment]
![loser-verlierer](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/assets/33746865/5459df45-f0a1-44eb-ba1e-66e07f46e30f)

**Comment by Ipuch** [comment]
I propose to just displace the row o the main table in another file to keep track of the last one with exclude...
in something like excluded_data.csv

**Comment by fmoissenet** [comment]
I have tried to give a last chance to this paper by extracting once again every information ...

Few comments:
- Orientations of the thorax were not well reported as the Fig.2 defines z as the sagittal axis (and not the mediolat axis)
- Segments are not defined by a frame but only by an axis (Y for scapula and humerus, Z for clavicle)
- The 3D angle between this "segment axis" and each global axis is then computed. Hence, for example in Fig. 6, the Y axes of the scapula and thorax, which were initially almost aligned (15° in the figure) go to 45°, while Y scapula was initially close to 90° to X global and go to 45°. But as Z global is pointing forward, there is almost not variation between Y scapula moving in the coronal plane and Z global. It means that for example a humerus 45° abduction, related to the thorax/global, will be seen as a 45° variation between Y humerus and Y global, but also between Y humerus and X global !! The reported angular variations are hence not comparable with what we obtain will Euler angles, and do not represent the physiological joint motions ! (hope to be clear).

Conclusion: kill it !

Florent.
