### ISSUE TITLE
Sahara et al. 2006

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#59]
We must consider corrections for segment clavicle, at least "to_isb_like".

> Joint acromioclavicular has no correction value in the parent segment clavicle, it should be filled with a Correction.TO_ISB_LIKE_ROTATION correction, because the segment is not isb. Current value: []
> Joint acromioclavicular has no correction value in the parent segment clavicle, it should be filled with a Correction.TO_ISB_LIKE_ROTATION correction, because the segment is not isb. Current value: []

**Comment by ANaaim** [comment]
I do not find the article anymore in the repertory to check ? Did we remove it ? ==> the article is still in the table

**Comment by Ipuch** [comment]
Missing Euler sequence.

**Comment by Ipuch** [comment]
The real problem is to handle the the fact it only contains translationnal data.
