### ISSUE TITLE
Sahara et al. 2007, thorax not direct

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#60]
> Sahara et al. 2007, Segment thorax is not direct, it should be !!!

Please still consider anteroposterior axis as pointing forward as #42 has not been closed yet.

**Comment by ANaaim** [comment]
I do not find the article anymore in the repertory to check ? Did we remove it ?

**Comment by Ipuch** [comment]
Done in #127
