### ISSUE TITLE
Sugi et al. 2001 Still missing corrections on scapula

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#61]
> Joint glenohumeral has no correction value in the parent segment scapula, it should be filled with a Correction.SCAPULA_KOLZ_AC_TO_PA_ROTATION or a Correction.SCAPULA_KOLZ_GLENOID_TO_PA_ROTATION correction,
because the segment origin is not on an isb axis. Current value: [<Correction.TO_ISB_ROTATION: 'to_isb'>]

- The segment scapula is not isb oriented and correctable through kolz. plz provide the right set of corrections: to_isb + any to kolz.

- The thorax is full of nan could we at least get the directions of the global frame ?

**Comment by Ipuch** [comment]
I'm okay with this.

**Comment by ANaaim** [comment]
@Ipuch  has corrected the data in the excel file

**Comment by Ipuch** [comment]
I still need to discuss corrections on the scapula.

It seems like the scapula is glenoid centered, and not correctable by Kolz:

![image](https://github.com/Ipuch/shoulder-kinematic-dataset/assets/40755537/207ac00c-31b2-4a22-a068-3a9770291295)

It would mean we are not able to get back any data from this study @fmoissenet.

**Comment by fmoissenet** [comment]
Scapula axes are related to anatomical axes. In this sense, we are in a ISB_like condition as the way the axes are defined dues not allow for any Kolz correction. For the reported rotations (GH and ST), we can consider to have a risk on data (probably offset). However, I agree that for this paper (and actually every other papers in the same case) that it may be difficult or impossible to report displacements if the coordinate system origin is not correct (and not correctable) and even more if axes are not ISB (and not correctable).

**Comment by Ipuch** [comment]
![image](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/assets/40755537/36ad2764-d80e-4a9c-bf7c-37c6f24b437b)

Should be set to false and may  be add the correction to PA also...
