### ISSUE TITLE
Play with plotly

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/spartacus-shoulder-kinematic-dataset#67]
Be able to generate a graph 3 by 3 with plotly with all the data in it. related to #24

**Comment by ANaaim** [comment]
![image](https://github.com/Ipuch/shoulder-kinematic-dataset/assets/33746865/46a03993-2570-4448-b193-0d47d2f3b186)

**Comment by ANaaim** [comment]
First try seems ok ==> How to have correct legend.

**Comment by Ipuch** [comment]
Yeah!

Don't hesitate to try theses features to match more scientific format.

 fig.update_layout(
            height=800,
            width=1500,
            paper_bgcolor="rgba(255,255,255,1)",
            plot_bgcolor="rgba(255,255,255,1)",
            legend=dict(
                title_font_family="Times New Roman",
                font=dict(family="Times New Roman", color="black", size=11),
                orientation="h",
                xanchor="center",
                x=0.5,
                y=-0.05,
            ),
            font=dict(
                size=12,
                family="Times New Roman",
            ),
            yaxis=dict(color="black"),       template="simple_white",
            boxgap=0.2,
        )

**Comment by ANaaim** [comment]
Great visual thanks !! Last stuff to manage is to have the text not cross each other. And for some cases, when there is multiple curves from the same data source (same article, same joint and same DoF) there is a line connecting the end of the data at the beginning of the next one.

![image](https://github.com/Ipuch/shoulder-kinematic-dataset/assets/33746865/0c56b1d7-d3b5-4bb4-a8fb-2f63a7318034)

**Comment by Ipuch** [comment]
I think it should look like this, with a class, what do you think ?

```python3 
figure = ShoulderKinematicFigure(
data=pandas.Dataframe,
motion="scapula_elevation",
)
figure.show()

# Ajouter des courbes supplémentaires
figure.add_curve_from_index(row=,col=,x,y)
figure.add_curve_from_name(joint="acromioclavicular",dof="elevation")  # maybe to complicated
figure.show()
figure.export()


```

**Comment by Ipuch** [comment]
Done I believe ! #108
