### ISSUE TITLE
[TO DO]  GH_planeOfElevation_elevationFrontal.csv is in the dataset but not in data for Lawrence 2014

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#89]
@fmoissenet any Idea ?

**Comment by fmoissenet** [comment]
Sure. The rotation sequence for glenohumeral kinematics was X-Z’-Y’’, not the Y-X’-Y’’ per ISB recommendations. Hence, the dataset is not correct. Attached the cells related to file names, corrected. Other motion file names have also been corrected.

[modif_Lawrence_et_al_2014.xlsx](https://github.com/Ipuch/spartacus-shoulder-kinematic-dataset/files/12780354/modif_Lawrence_et_al_2014.xlsx)

**Comment by fmoissenet** [comment]
To be managed: Lawrence et al. is the only paper we have were GH rotations have been obtained from XZY Euler sequence instead of YXY (ISB). A data transformation is requested before data comparison.

**Comment by Ipuch** [comment]
I just need to update the .csv
