### ISSUE TITLE
[TO DISCUSS]  When data comes from engauge, thoracohumeral abscissa need to be averaged.

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#90]
Do you agree on the fact that when I get back data from engauge, I will average the data over the three DOFs ?
I would mitigate the clicking precision.

If both Yes then I will close this issue:
@ANaaim 
@fmoissenet

**Comment by ANaaim** [comment]
I agree 👍  Seems logical to me... the point are supposed to share a similar abscissa.

**Comment by fmoissenet** [comment]
OK for me too.
