### ISSUE TITLE
[TO DISCUSS]  /Fung et al 2001/SC_tilt_FrontalPlane.csv'

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#94]
Not in the data but in the .csv file.
@fmoissenet let me know if it requires a PR.

**Comment by fmoissenet** [comment]
Not sur to understand the issue. I confirm that:
- The information is available in the original paper
- The file is listed in the extraction table (line 23)
- The .csv file is available

No need for a PR for me.
